[package]
name = "multi-threaded-web-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.18"
clap = { version = "4.0", features = ["derive"] }
url = "2.4"
thiserror = "1.0"

[dev-dependencies]
mockito = "1.2"